@MythicalCreatures_HostAddress = http://localhost:5064
@id = 2

GET {{MythicalCreatures_HostAddress}}/creatures/
Accept: application/json

###

GET {{MythicalCreatures_HostAddress}}/creatures/{{id}}
Accept: application/json

###

POST {{MythicalCreatures_HostAddress}}/creatures
Content-Type: application/json

{
    "name": "Jussi",
    "type": "Lil egg",
    "strength": 0
}

###

PUT {{MythicalCreatures_HostAddress}}/creatures/{{id}}
Content-Type: application/json

{
    "id": {{id}},
    "name": "Pip pop",
    "type": "Blob",
    "agility": 1
}

###

DELETE {{MythicalCreatures_HostAddress}}/creatures/{{id}}