@AuthorisationApi_HostAddress = http://localhost:7092

GET {{AuthorisationApi_HostAddress}}/Users/
Accept: application/json

###

// Käyttäjän luominen
POST http://localhost:7092/Users
Content-Type: application/json

{
    "userName": "newuser",
    "password": "newpassword"
}

// Kirjautuminen
POST http://localhost:7092/Users/Login
Content-Type: application/json

{
    "userName": "newuser",
    "password": "newpassword"
}

