@AuthorisationApi_HostAddress = http://localhost:5052

GET {{AuthorisationApi_HostAddress}}/Users/
Accept: application/json

###

// Käyttäjän luominen
POST {{AuthorisationApi_HostAddress}}/Users
Content-Type: application/json

{
    "userName": "newuser",
    "password": "newpassword"
}


###
// Kirjautuminen
POST http://localhost:5052/Users/Login
Content-Type: application/json

{
    "userName": "newuser",
    "password": "newpassword"
}

